### ISSUE TITLE
Navigation Bar Home Page

### ISSUE THREAD

**Issue by evan03121998** [inxudianz/Creativ#12]
elp.. color navbar bermasalah

**Comment by inxudianz** [comment]
`if #available(iOS 13.0, *) {
    let navBarAppearance = UINavigationBarAppearance()
    navBarAppearance.configureWithOpaqueBackground()
    navBarAppearance.titleTextAttributes = [.foregroundColor: UIColor.white]
    navBarAppearance.largeTitleTextAttributes = [.foregroundColor: UIColor.white]
    navBarAppearance.backgroundColor = <insert your color here>
    navigationBar.standardAppearance = navBarAppearance
    navigationBar.scrollEdgeAppearance = navBarAppearance
}`

pake ini di UINavigationController bisa coloured status barnya
